// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdg2tQ-4fpUB_8JF57v48hpgbvuxkEk_k',
    appId: '1:303696250839:web:0f84b26c8180cdbc9c6d92',
    messagingSenderId: '303696250839',
    projectId: 'workout-tracker-app-2bccf',
    authDomain: 'workout-tracker-app-2bccf.firebaseapp.com',
    storageBucket: 'workout-tracker-app-2bccf.firebasestorage.app',
    measurementId: 'G-1GKVSZCREN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp8o-tt_aDbneGC1KpdAjv4ABlfOKlSr0',
    appId: '1:303696250839:android:d5e8dee5aa1a2b9c9c6d92',
    messagingSenderId: '303696250839',
    projectId: 'workout-tracker-app-2bccf',
    storageBucket: 'workout-tracker-app-2bccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk04sQeRYkYb4oRBt1VZgWg4aOBif8J5M',
    appId: '1:303696250839:ios:80d568158cede1519c6d92',
    messagingSenderId: '303696250839',
    projectId: 'workout-tracker-app-2bccf',
    storageBucket: 'workout-tracker-app-2bccf.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk04sQeRYkYb4oRBt1VZgWg4aOBif8J5M',
    appId: '1:303696250839:ios:80d568158cede1519c6d92',
    messagingSenderId: '303696250839',
    projectId: 'workout-tracker-app-2bccf',
    storageBucket: 'workout-tracker-app-2bccf.firebasestorage.app',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdg2tQ-4fpUB_8JF57v48hpgbvuxkEk_k',
    appId: '1:303696250839:web:6b4fc45c739d71239c6d92',
    messagingSenderId: '303696250839',
    projectId: 'workout-tracker-app-2bccf',
    authDomain: 'workout-tracker-app-2bccf.firebaseapp.com',
    storageBucket: 'workout-tracker-app-2bccf.firebasestorage.app',
    measurementId: 'G-FPTEPP8GE7',
  );
}
